import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Main from "../components/main";
import Info from "../components/info";
import Detail from "../components/detail";
import Highlight from "../components/highlight";
import Carousel from "../components/carousel";
import Footer from "../components/footer";
import Book from "../components/book";
import { highlight } from "../data/highlight";

export default function Home() {
    return (
        <div className={styles.main_container}>
            <Head>
                <title>Frontend Mentor | Dine Website Challenge</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon-32x32.png" />
            </Head>

            <Main />

            <section
                className={styles.section_more_info}
                aria-label="more informations"
            >
                <Info
                    container_position="container_position"
                    position="detail_position"
                    img_position="top"
                    desktop="./images/homepage/enjoyable-place-desktop.jpg"
                    tablet="./images/homepage/enjoyable-place-tablet.jpg"
                    mobile="./images/homepage/enjoyable-place-mobile.jpg"
                    detail={
                        <Detail
                            header="  Enjoyable place for all the family"
                            paragraph=" Our relaxed surroundings make dining with us a great experience for everyone. We can even arrange 
                                                          a tour of the farm before your meal."
                            color="black"
                        />
                    }
                />
                <Info
                    lines="lines"
                    img_position="bottom"
                    order="picture_order"
                    desktop="./images/homepage/locally-sourced-desktop.jpg"
                    tablet="./images/homepage/locally-sourced-tablet.jpg"
                    mobile="./images/homepage/locally-sourced-mobile.jpg"
                    detail={
                        <Detail
                            header="The most locally sourced food"
                            paragraph=" All our ingredients come directly from our farm or local fishery. So you can be sure that you’re 
                                              eating the freshest, most sustainable food."
                            color="black"
                        />
                    }
                />
            </section>
            <section
                className={styles.section_highlights}
                aria-label="highlights"
            >
                <div className={styles.container_highlights}>
                    <Detail
                        header="A few highlights from our menu"
                        paragraph="We cater for all dietary requirements, but here’s a glimpse at some of our diner’s favourites. 
                                            Our menu is revamped every season."
                        color="white"
                    />
                    <div className={styles.box_highlights}>
                        {highlight.map(item => (
                            <Highlight
                                key={item.id}
                                desktop={item.desktop}
                                mobile={item.mobile}
                                header={item.header}
                                paragraph={item.paragraph}
                                line={item.line ? <hr /> : null}
                            />
                        ))}
                    </div>
                </div>
            </section>

            <section className={styles.section_slides} aria-label="slides">
                <div className={styles.carousel_wrap}>
                    <Carousel />
                </div>
            </section>
            <section
                className={styles.section_riservation}
                aria-label="reservation"
            >
                <div className={styles.reservation_container}>
                    <h2> Ready to make a reservation?</h2>

                    <Book color="transparent" />
                </div>
            </section>

            <Footer />
        </div>
    );
}
